### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [nescomtm/zad_83#1]
- [x] html - popraw wciecia i kodowanie pliku
- [x] usun z package.json `grunt-contrib-imagemin` - nie uzywasz, a niepotrzebnie to sie sciaga przez npm install
- [x] jshint dziala - mozna dodac srednik

**Comment by nescomtm** [comment]
naniosłem poprawki według zaleceń
